const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('C:/Users/gdove/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root='C:/Users/gdove/OneDrive/Desktop/GOOOL',base=process.argv[2],label=process.argv[3]||'preview';
if(!/^https:\/\/(?:goool\.shop|[a-f0-9]+--goool-shop\.netlify\.app)$/.test(base))throw Error('Unexpected deployment host');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{
const report={base,checkedAt:new Date().toISOString(),publicGate:null,images:[],pages:[],optimizer:[]};
const gate=await fetch(base+'/shop',{redirect:'manual'});report.publicGate={status:gate.status,location:gate.headers.get('location')};if(gate.status!==200)throw Error('Public storefront is not open');
const headers={};
const records=require('./verification.json').records;
for(let i=0;i<records.length;i+=6)await Promise.all(records.slice(i,i+6).map(async rec=>{const r=await fetch(base+rec.src+'?v=backdrop-20260925',{headers,redirect:'manual'});const b=Buffer.from(await r.arrayBuffer());const row={src:rec.src,status:r.status,byteMatch:hash(b)===rec.outputSha256};report.images.push(row);if(r.status!==200||!row.byteMatch)throw Error('Asset verification failed '+rec.src+' status '+r.status);}));
for(const p of ['/', '/shop','/cart','/robots.txt','/sitemap.xml',...require('./catalog.json').map(p=>'/shop/'+p.slug)]){const r=await fetch(base+p,{headers,redirect:'manual'}),html=await r.text();const row={path:p,status:r.status,versionedCatalogImages:html.includes('backdrop-20260925')};report.pages.push(row);if(r.status!==200)throw Error('Page failed '+p);if(p==='/robots.txt'&&!html.includes('Allow: /'))throw Error('Robots does not permit indexing');if(p==='/sitemap.xml'&&!html.includes('https://goool.shop/shop/'))throw Error('Sitemap missing products');if(['/', '/shop'].includes(p)&&(/name="robots"[^>]*noindex/i.test(html)||/noindex/i.test(r.headers.get('x-robots-tag')||'')))throw Error('Storefront has noindex');}
for(const rec of records){const url=base+'/_next/image?url='+encodeURIComponent(rec.src+'?v=backdrop-20260925')+'&w=640&q=90';const r=await fetch(url,{headers:{...headers,accept:'image/webp'},redirect:'manual'});const b=Buffer.from(await r.arrayBuffer());if(r.status!==200||!r.headers.get('content-type')?.startsWith('image/'))throw Error('Optimizer failed '+rec.src);const {data,info}=await sharp(b).removeAlpha().raw().toBuffer({resolveWithObject:true});const points=[0,info.width-1,10*info.width+10].map(i=>Array.from(data.subarray(i*3,i*3+3)));if(points.some(p=>p.some(v=>Math.abs(v-242)>1)))throw Error('Optimized backdrop mismatch '+rec.src);report.optimizer.push({src:rec.src,status:r.status,type:r.headers.get('content-type'),bytes:b.byteLength,backgroundSamples:points});}
fs.writeFileSync(path.join(__dirname,'verified-'+label+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({base,gate:report.publicGate,images:report.images.length,byteMatches:report.images.filter(x=>x.byteMatch).length,pages:report.pages.length,optimizedImages:report.optimizer.length,allPassed:true}));
})().catch(e=>{console.error(e.message);process.exit(1)});
