import { Product, SHIRT_SIZES, ONE_SIZE, ProductCategory } from "./types";

// ─────────────────────────────────────────────────────────────
// Launch catalog — Drop Version I.
// Mirrors the Supabase `products` table exactly (same UUIDs as the
// seed migration). Swap `getProducts()` / `getProductBySlug()` for
// Supabase queries later and nothing else changes.
//
// Image paths point at /public/products/*.svg placeholders — replace
// each SVG with a real product photo when photography is ready.
// ─────────────────────────────────────────────────────────────

const JERSEY_FABRIC =
  "Lightweight performance knit. 100% recycled polyester. Moisture-wicking and breathable with a silky smooth finish, printed edge to edge.";
const CASUAL_FABRIC =
  "Soft 100% ring-spun cotton staple tee. Lightweight and breathable — holds color, holds shape, feels broken-in from day one.";
const HEAVY_FABRIC =
  "Heavyweight garment-dyed 100% cotton. Oversized cut with real weight and structure.";

const JERSEY_CARE =
  "Machine wash cold, inside out. No bleach. Hang dry. Do not iron the print.";
const CASUAL_CARE =
  "Machine wash cold with like colors. Tumble dry low. Do not iron the print.";
const ACCESSORY_CARE = "Spot clean or hand wash cold. Lay flat to dry.";

const JERSEY_FIT = "Athletic fit. True to size. Size up for a relaxed feel.";
const CASUAL_FIT = "Relaxed fit. Between sizes? Stay true.";
const OVERSIZED_FIT = "Oversized fit. Drops loose on purpose. Size down for a standard fit.";

const PERF_FABRIC =
  "Moisture-wicking 100% polyester performance knit (Gildan Performance). Lightweight, breathable, DTF printed.";
const PERF_FIT = "Athletic cut. True to size.";
const PERF_CARE = "Machine wash cold. Tumble dry low. Do not iron the print.";

const CUSTOMIZATION_PRICE = 1500; // $15 name/number add-on (jerseys only)

// Shared drop settings per collection drop.
const DROP_I = {
  isLimitedDrop: true,
  dropVersion: "I",
  dropLimit: 500,
};
const DROP_II = {
  isLimitedDrop: false,
  dropVersion: "II", // collection identity only — no scarcity claims (POD)
  dropLimit: null,
};

export const products: Product[] = [
  // ── Performance Jersey Collection ───────────────────────────
  {
    id: "10000000-0000-4000-8000-000000000001",
    name: "Home Red Jersey",
    slug: "home-red-jersey",
    description:
      "The one you wear when it matters. Silky, breathable performance knit made for the moment it goes in.",
    priceCents: 6100,
    compareAtPriceCents: null,
    color: "Deep Red",
    colorHex: "#C1121F",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/home-red-jersey.webp", alt: "Home Red Jersey — front, on model" },
      { src: "/products/home-red-jersey-back.webp", alt: "Home Red Jersey — back, ready for custom name and number" },
    ],
    sizes: SHIRT_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_I,
    dropSoldCount: 212,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    name: "Away White Jersey",
    slug: "away-white-jersey",
    description:
      "Clean and loud at the same time. A crisp away-style jersey that shows up in every crowd photo.",
    priceCents: 6100,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/away-white-jersey.webp", alt: "Away White Jersey — front, on model" },
      { src: "/products/away-white-jersey-back.webp", alt: "Away White Jersey — back, ready for custom name and number" },
    ],
    sizes: SHIRT_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_I,
    dropSoldCount: 148,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    name: "Blackout Edition Jersey",
    slug: "blackout-edition-jersey",
    description:
      "All black, gold detail, zero apologies. The limited edition for fans who don't need to be told the score.",
    priceCents: 6100,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/blackout-edition-jersey.webp", alt: "Blackout Edition Jersey — front, on model" },
      { src: "/products/blackout-edition-jersey-back.webp", alt: "Blackout Edition Jersey — back, ready for custom name and number" },
    ],
    sizes: SHIRT_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_I,
    dropSoldCount: 373,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },
  {
    id: "10000000-0000-4000-8000-000000000004",
    name: "Emerald Edition Jersey",
    slug: "emerald-edition-jersey",
    description:
      "Deep green with gold accents. A nation's color, cut for match day and everything after.",
    priceCents: 6100,
    compareAtPriceCents: null,
    color: "Emerald Green",
    colorHex: "#0B3D2E",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/emerald-edition-jersey.webp", alt: "Emerald Edition Jersey — front, on model" },
      { src: "/products/emerald-edition-jersey-back.webp", alt: "Emerald Edition Jersey — back, ready for custom name and number" },
    ],
    sizes: SHIRT_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_I,
    dropSoldCount: 84,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },


  // == ENGOOOLAND - The England Collection / Drop 02 ==========
  {
    id: "10000000-0000-4000-8000-000000000005",
    name: "ENGOOOLAND Home White Jersey",
    slug: "engoooland-home-white-jersey",
    description:
      "The scream, embedded. Crisp white with the red and navy sash — chapter two starts loud.",
    priceCents: 6500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/engoooland-home-white-jersey.webp", alt: "ENGOOOLAND Home White Jersey — front, on model" },
      { src: "/products/engoooland-home-white-jersey-ghost.webp", alt: "ENGOOOLAND jersey — exact fit, front view" },
      { src: "/products/engoooland-home-white-jersey-back.webp", alt: "ENGOOOLAND Home White Jersey — back, ready for custom name and number" },
    ],
    sizes: SHIRT_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: true,
    ...DROP_II,
    dropSoldCount: 0,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },
  {
    id: "10000000-0000-4000-8000-000000000006",
    name: "ENGOOOLAND Away Red Jersey",
    slug: "engoooland-away-red-jersey",
    description:
      "Deep red with white and navy movement. For the away days and the loud ends.",
    priceCents: 6500,
    compareAtPriceCents: null,
    color: "Deep Red",
    colorHex: "#C1121F",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/engoooland-away-red-jersey.webp", alt: "ENGOOOLAND Away Red Jersey — front, on model" },
      { src: "/products/engoooland-away-red-jersey-ghost.webp", alt: "ENGOOOLAND jersey — exact fit, front view" },
      { src: "/products/engoooland-away-red-jersey-back.webp", alt: "ENGOOOLAND Away Red Jersey — back, ready for custom name and number" },
    ],
    sizes: SHIRT_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: true,
    ...DROP_II,
    dropSoldCount: 0,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },
  {
    id: "10000000-0000-4000-8000-000000000007",
    name: "ENGOOOLAND Navy Jersey",
    slug: "engoooland-navy-jersey",
    description:
      "England Navy with the red-white sash and a gold pinline. Quiet colour, loud intent.",
    priceCents: 6500,
    compareAtPriceCents: null,
    color: "England Navy",
    colorHex: "#0A1F3C",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/engoooland-navy-jersey.webp", alt: "ENGOOOLAND Navy Jersey — front, on model" },
      { src: "/products/engoooland-navy-jersey-ghost.webp", alt: "ENGOOOLAND jersey — exact fit, front view" },
      { src: "/products/engoooland-navy-jersey-back.webp", alt: "ENGOOOLAND Navy Jersey — back, ready for custom name and number" },
    ],
    sizes: SHIRT_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: true,
    ...DROP_II,
    dropSoldCount: 0,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },

  // ── Casual Shirt Collection ─────────────────────────────────
  {
    id: "20000000-0000-4000-8000-000000000001",
    name: "PORTUGOOOL Brush Script Tee",
    slug: "brush-script-tee",
    description:
      "The brand name in one loud stroke. Soft, heavy, and easy to live in.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/brush-script-tee.webp", alt: "PORTUGOOOL Brush Script Tee — front" },
      { src: "/products/brush-script-tee-back.webp", alt: "PORTUGOOOL Brush Script Tee — back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000002",
    name: "GOOOOOOOL!!! Tee",
    slug: "goool-tee",
    description:
      "The whole moment in one word. Wear the celebration.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "Deep Red",
    colorHex: "#C1121F",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/goool-tee.webp", alt: "GOOOOOOOL!!! Tee — front" },
      { src: "/products/goool-tee-back.webp", alt: "GOOOOOOOL!!! Tee — back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000003",
    name: "Vamos Portugooool Tee",
    slug: "vamos-tee",
    description:
      "For the ones who start the chant. Soft-touch blend built for watch parties.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "Emerald Green",
    colorHex: "#0B3D2E",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/vamos-tee.webp", alt: "Vamos Portugooool Tee — front" },
      { src: "/products/vamos-tee-back.webp", alt: "Vamos Portugooool Tee — back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000004",
    name: "From Lisbon to the World Tee",
    slug: "lisbon-to-the-world-tee",
    description:
      "One city, every living room, every corner bar. This one travels.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/lisbon-to-the-world-tee.webp", alt: "From Lisbon to the World Tee — front" },
      { src: "/products/lisbon-to-the-world-tee-back.webp", alt: "From Lisbon to the World Tee — back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000005",
    name: "Match Day Tee",
    slug: "match-day-tee",
    description:
      "Some days are just different. Dress accordingly.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "Smoke Grey",
    colorHex: "#9CA3AF",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/match-day-tee.webp", alt: "Match Day Tee — front" },
      { src: "/products/match-day-tee-back.webp", alt: "Match Day Tee — back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000006",
    name: "We Don't Whisper Goals Tee",
    slug: "we-dont-whisper-goals-tee",
    description:
      "Heavyweight, oversized, and honest about who you are during a match.",
    priceCents: 3300,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: HEAVY_FABRIC,
    fit: OVERSIZED_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/we-dont-whisper-goals-tee.webp", alt: "We Don't Whisper Goals Tee — front" },
      { src: "/products/we-dont-whisper-goals-tee-back.webp", alt: "We Don't Whisper Goals Tee — back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },


  // == England Collection casual tees (Drop 02) ===============
  {
    id: "20000000-0000-4000-8000-000000000007",
    name: "ENGOOOLAND Echo Hero Tee",
    slug: "engoooland-echo-hero-tee",
    description:
      "The Echo, oversized, in red and navy. Chapter two on a clean white staple.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/engoooland-echo-hero-tee.webp", alt: "ENGOOOLAND Echo Hero Tee — front" },
      { src: "/products/engoooland-echo-hero-tee-back.webp", alt: "ENGOOOLAND Echo Hero Tee — back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000008",
    name: "From London to the World Tee",
    slug: "london-to-the-world-tee",
    description:
      "One city, every corner bar. The London mirror of a Lisbon classic.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "England Navy",
    colorHex: "#0A1F3C",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/london-to-the-world-tee.webp", alt: "From London to the World Tee — front" },
      { src: "/products/london-to-the-world-tee-back.webp", alt: "From London to the World Tee — back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000009",
    name: "Made for the Moment Tee",
    slug: "made-for-the-moment-tee",
    description:
      "The tagline, front and center. Deep red, built for the second it goes in.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "Deep Red",
    colorHex: "#C1121F",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/made-for-the-moment-tee.webp", alt: "Made for the Moment Tee — front" },
      { src: "/products/made-for-the-moment-tee-back.webp", alt: "Made for the Moment Tee — back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000010",
    name: "ENGOOOLAND Roar Tee",
    slug: "engoooland-roar-tee",
    description:
      "Echo badge at the breast, the moment stacked beneath. Navy, understated, ready.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "England Navy",
    colorHex: "#0A1F3C",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/engoooland-roar-tee.webp", alt: "ENGOOOLAND Roar Tee — front" },
      { src: "/products/engoooland-roar-tee-back.webp", alt: "ENGOOOLAND Roar Tee — back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },


  // == GOL House Line - performance tees (Printify/SwiftPOD) ==
  {
    id: "40000000-0000-4000-8000-000000000007",
    name: "GOL Clean Sheet Tee",
    slug: "gol-clean-sheet-tee",
    description:
      "The mark in ink on clean white. Performance fabric, daylight energy.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: PERF_FABRIC,
    fit: PERF_FIT,
    careInstructions: PERF_CARE,
    images: [
      { src: "/products/gol-clean-sheet-tee.webp", alt: "GOL Clean Sheet Tee — front" },
      { src: "/products/gol-clean-sheet-tee-alt.webp", alt: "GOL Clean Sheet Tee — detail" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printify",
    isActive: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "40000000-0000-4000-8000-000000000008",
    name: "GOL Gold Standard Tee",
    slug: "gol-gold-standard-tee",
    description:
      "Gold on black with a tonal slash. The house look, built to move.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: PERF_FABRIC,
    fit: PERF_FIT,
    careInstructions: PERF_CARE,
    images: [
      { src: "/products/gol-gold-standard-tee.webp", alt: "GOL Gold Standard Tee — front" },
      { src: "/products/gol-gold-standard-tee-alt.webp", alt: "GOL Gold Standard Tee — detail" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printify",
    isActive: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "40000000-0000-4000-8000-000000000009",
    name: "GOL Concrete Tee",
    slug: "gol-concrete-grey-tee",
    description:
      "The slash oversized, the mark up top. Street energy on performance poly.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Sport Grey",
    colorHex: "#9CA3AF",
    fabric: PERF_FABRIC,
    fit: PERF_FIT,
    careInstructions: PERF_CARE,
    images: [
      { src: "/products/gol-concrete-grey-tee.webp", alt: "GOL Concrete Tee — front" },
      { src: "/products/gol-concrete-grey-tee-alt.webp", alt: "GOL Concrete Tee — detail" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printify",
    isActive: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "40000000-0000-4000-8000-000000000010",
    name: "GOL Concrete White Tee",
    slug: "gol-concrete-white-tee",
    description:
      "Ink slash shoulder to hip, gold lockup. The loud one in white.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: PERF_FABRIC,
    fit: PERF_FIT,
    careInstructions: PERF_CARE,
    images: [
      { src: "/products/gol-concrete-white-tee.webp", alt: "GOL Concrete White Tee — front" },
      { src: "/products/gol-concrete-white-tee-alt.webp", alt: "GOL Concrete White Tee — detail" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printify",
    isActive: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "40000000-0000-4000-8000-000000000011",
    name: "GOL Concrete Black Tee",
    slug: "gol-concrete-black-tee",
    description:
      "Paper slash, gold mark. Blackout energy for the performance line.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: PERF_FABRIC,
    fit: PERF_FIT,
    careInstructions: PERF_CARE,
    images: [
      { src: "/products/gol-concrete-black-tee.webp", alt: "GOL Concrete Black Tee — front" },
      { src: "/products/gol-concrete-black-tee-alt.webp", alt: "GOL Concrete Black Tee — detail" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printify",
    isActive: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },

  // ── Accessory Collection ────────────────────────────────────
  {
    id: "30000000-0000-4000-8000-000000000001",
    name: "Supporters Scarf",
    slug: "supporters-scarf",
    description:
      "Double-sided knit scarf. Raise it at kickoff, wear it home after.",
    priceCents: 2800,
    compareAtPriceCents: null,
    color: "Red / Green",
    colorHex: "#C1121F",
    fabric: "Double-sided acrylic knit with fringed ends. Stadium-weight.",
    fit: "One size · 145 × 18 cm.",
    careInstructions: ACCESSORY_CARE,
    images: [
      { src: "/products/supporters-scarf.svg", alt: "Supporters Scarf" },
    ],
    sizes: ONE_SIZE,
    category: "accessory",
    supplierType: "unassigned",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "30000000-0000-4000-8000-000000000002",
    name: "GOOOOOL Cap",
    slug: "goool-cap",
    description:
      "Low-profile cap with the sound of victory stitched on the front.",
    priceCents: 2900,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "Brushed cotton twill, embroidered front, adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: ACCESSORY_CARE,
    images: [{ src: "/products/goool-cap.svg", alt: "GOOOOOL Cap" }],
    sizes: ONE_SIZE,
    category: "accessory",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "30000000-0000-4000-8000-000000000003",
    name: "Sticker Pack",
    slug: "sticker-pack",
    description:
      "Six die-cut stickers. Laptops, bottles, and anything else that needs more noise.",
    priceCents: 1000,
    compareAtPriceCents: null,
    color: "Multi",
    colorHex: "#C9A227",
    fabric: "Kiss-cut matte vinyl sticker sheet. Six designs on one sheet.",
    fit: "One sheet · 5.83″ × 8.27″ · six stickers.",
    careInstructions: "Peel and place once.",
    images: [{ src: "/products/sticker-pack.svg", alt: "Sticker Pack — six die-cut stickers" }],
    sizes: ONE_SIZE,
    category: "accessory",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "30000000-0000-4000-8000-000000000004",
    name: "Terrace Flag",
    slug: "terrace-flag",
    description:
      "90 × 150 cm of pure celebration. For balconies, backyards, and full-time whistles.",
    priceCents: 2400,
    compareAtPriceCents: null,
    color: "Red / Green / Gold",
    colorHex: "#0B3D2E",
    fabric: "Lightweight knitted polyester with reinforced grommets.",
    fit: "One size · 90 × 150 cm.",
    careInstructions: ACCESSORY_CARE,
    images: [{ src: "/products/terrace-flag.svg", alt: "Terrace Flag" }],
    sizes: ONE_SIZE,
    category: "accessory",
    supplierType: "unassigned",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },

  // == GOL caps (Printful embroidery, Yupoong 6245CM) =========
  {
    id: "50000000-0000-4000-8000-000000000001",
    name: "GOL Cap Black",
    slug: "gol-cap-black",
    description:
      "Gold GOL, stitched. Low-profile classic cap, adjustable strap.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "Brushed cotton twill, embroidered GOL mark, adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/gol-cap-black.webp", alt: "GOL Cap Black — front" },
      { src: "/products/gol-cap-black-alt.webp", alt: "GOL Cap Black — angle" },
    ],
    sizes: ONE_SIZE,
    category: "accessory",
    supplierType: "printful",
    isActive: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000002",
    name: "GOL Cap White",
    slug: "gol-cap-white",
    description:
      "Ink GOL, stitched clean on white. Low-profile classic cap, adjustable strap.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: "Brushed cotton twill, embroidered GOL mark, adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/gol-cap-white.webp", alt: "GOL Cap White — front" },
      { src: "/products/gol-cap-white-alt.webp", alt: "GOL Cap White — angle" },
    ],
    sizes: ONE_SIZE,
    category: "accessory",
    supplierType: "printful",
    isActive: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
];

// ── Data access (swap these for Supabase queries later) ───────

export function getProducts(): Product[] {
  return products.filter((p) => p.isActive);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug && p.isActive);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id && p.isActive);
}

export function getLimitedDropProducts(): Product[] {
  return products.filter((p) => p.isActive && p.isLimitedDrop);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return products.filter((p) => p.isActive && p.category === category);
}

export function getJerseysByDrop(version: string): Product[] {
  return products.filter(
    (p) => p.isActive && p.category === "jersey" && p.dropVersion === version
  );
}
