import { Product, SHIRT_SIZES, JERSEY_SIZES, OVERSIZED_TEE_SIZES, ONE_SIZE, ProductCategory } from "./types";

// ─────────────────────────────────────────────────────────────
// Launch catalog · Drop Version I.
// Mirrors the Supabase `products` table exactly (same UUIDs as the
// seed migration). Swap `getProducts()` / `getProductBySlug()` for
// Supabase queries later and nothing else changes.
//
// Image paths point at /public/products/*.svg placeholders · replace
// each SVG with a real product photo when photography is ready.
// ─────────────────────────────────────────────────────────────

const JERSEY_FABRIC =
  "Lightweight performance knit. 100% recycled polyester. Moisture-wicking and breathable with a silky smooth finish, printed edge to edge.";
const CASUAL_FABRIC =
  "Soft 100% ring-spun cotton staple tee. Lightweight and breathable. Holds color, holds shape, and feels broken-in from day one.";
const HEAVY_FABRIC =
  "Heavyweight garment-dyed 100% cotton. Oversized cut with real weight and structure.";

const JERSEY_CARE =
  "Machine wash cold, inside out. No bleach. Hang dry. Do not iron the print.";
const CASUAL_CARE =
  "Machine wash cold with like colors. Tumble dry low. Do not iron the print.";
const ACCESSORY_CARE = "Spot clean or hand wash cold. Lay flat to dry.";

const JERSEY_FIT = "Athletic fit. True to size. Size up for a relaxed feel.";
const CASUAL_FIT = "Relaxed fit. Between sizes? Stay true.";
const OVERSIZED_FIT = "Oversized fit. Drops loose on purpose. Size down for a standard fit.";

const PERF_FABRIC =
  "Moisture-wicking 100% polyester performance knit (Gildan Performance). Lightweight, breathable, DTF printed.";
const PERF_FIT = "Athletic cut. True to size.";
const PERF_CARE = "Machine wash cold. Tumble dry low. Do not iron the print.";

const CUSTOMIZATION_PRICE = 1500; // $15 name/number add-on (jerseys only)

// Shared drop settings per collection drop.
const DROP_I = {
  isLimitedDrop: true,
  dropVersion: "I",
  dropLimit: 500,
};
const DROP_II = {
  isLimitedDrop: false,
  dropVersion: "II", // collection identity only, no scarcity claims (POD)
  dropLimit: null,
};

export const products: Product[] = [
  // ── Performance Jersey Collection ───────────────────────────
  {
    id: "10000000-0000-4000-8000-000000000001",
    name: "Home Red Jersey",
    slug: "home-red-jersey",
    description:
      "The one you wear when it matters. Silky, breathable performance knit made for the moment it goes in.",
    priceCents: 6100,
    compareAtPriceCents: null,
    color: "Deep Red",
    colorHex: "#C1121F",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/home-red-jersey.webp", alt: "Home Red Jersey · front, on model" },
      { src: "/products/home-red-jersey-back.webp", alt: "Home Red Jersey · back, ready for custom name and number" },
    ],
    sizes: JERSEY_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_I,
    dropSoldCount: 212,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    name: "Away White Jersey",
    slug: "away-white-jersey",
    description:
      "Clean and loud at the same time. A crisp away-style jersey that shows up in every crowd photo.",
    priceCents: 6100,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/away-white-jersey.webp", alt: "Away White Jersey · front, on model" },
      { src: "/products/away-white-jersey-back.webp", alt: "Away White Jersey · back, ready for custom name and number" },
    ],
    sizes: JERSEY_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_I,
    dropSoldCount: 148,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    name: "Blackout Edition Jersey",
    slug: "blackout-edition-jersey",
    description:
      "All black, gold detail, zero apologies. The limited edition for fans who don't need to be told the score.",
    priceCents: 6100,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/blackout-edition-jersey.webp", alt: "Blackout Edition Jersey · front, on model" },
      { src: "/products/blackout-edition-jersey-back.webp", alt: "Blackout Edition Jersey · back, ready for custom name and number" },
    ],
    sizes: JERSEY_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_I,
    dropSoldCount: 373,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },
  {
    id: "10000000-0000-4000-8000-000000000004",
    name: "Emerald Edition Jersey",
    slug: "emerald-edition-jersey",
    description:
      "Deep green with gold accents. A nation's color, cut for match day and everything after.",
    priceCents: 6100,
    compareAtPriceCents: null,
    color: "Emerald Green",
    colorHex: "#0B3D2E",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/emerald-edition-jersey.webp", alt: "Emerald Edition Jersey · front, on model" },
      { src: "/products/emerald-edition-jersey-back.webp", alt: "Emerald Edition Jersey · back, ready for custom name and number" },
    ],
    sizes: JERSEY_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_I,
    dropSoldCount: 84,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },


  // == ENGOOOLAND - The England Collection / Drop 02 ==========
  {
    id: "10000000-0000-4000-8000-000000000005",
    name: "ENGOOOLAND Home White Jersey",
    slug: "engoooland-home-white-jersey",
    description:
      "The scream, embedded. Crisp white with the red and navy sash. Chapter two starts loud.",
    priceCents: 6500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/engoooland-home-white-jersey.webp", alt: "ENGOOOLAND Home White Jersey · front, on model" },
      { src: "/products/engoooland-home-white-jersey-ghost.webp", alt: "ENGOOOLAND jersey · exact fit, front view" },
      { src: "/products/engoooland-home-white-jersey-back.webp", alt: "ENGOOOLAND Home White Jersey · back, ready for custom name and number" },
    ],
    sizes: JERSEY_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_II,
    dropSoldCount: 0,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },
  {
    id: "10000000-0000-4000-8000-000000000006",
    name: "ENGOOOLAND Away Red Jersey",
    slug: "engoooland-away-red-jersey",
    description:
      "Deep red with white and navy movement. For the away days and the loud ends.",
    priceCents: 6500,
    compareAtPriceCents: null,
    color: "Deep Red",
    colorHex: "#C1121F",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/engoooland-away-red-jersey.webp", alt: "ENGOOOLAND Away Red Jersey · front, on model" },
      { src: "/products/engoooland-away-red-jersey-ghost.webp", alt: "ENGOOOLAND jersey · exact fit, front view" },
      { src: "/products/engoooland-away-red-jersey-back.webp", alt: "ENGOOOLAND Away Red Jersey · back, ready for custom name and number" },
    ],
    sizes: JERSEY_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_II,
    dropSoldCount: 0,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },
  {
    id: "10000000-0000-4000-8000-000000000007",
    name: "ENGOOOLAND Navy Jersey",
    slug: "engoooland-navy-jersey",
    description:
      "England Navy with the red-white sash and a gold pinline. Quiet colour, loud intent.",
    priceCents: 6500,
    compareAtPriceCents: null,
    color: "England Navy",
    colorHex: "#0A1F3C",
    fabric: JERSEY_FABRIC,
    fit: JERSEY_FIT,
    careInstructions: JERSEY_CARE,
    images: [
      { src: "/products/engoooland-navy-jersey.webp", alt: "ENGOOOLAND Navy Jersey · front, on model" },
      { src: "/products/engoooland-navy-jersey-ghost.webp", alt: "ENGOOOLAND jersey · exact fit, front view" },
      { src: "/products/engoooland-navy-jersey-back.webp", alt: "ENGOOOLAND Navy Jersey · back, ready for custom name and number" },
    ],
    sizes: JERSEY_SIZES,
    category: "jersey",
    supplierType: "printful",
    isActive: false,
    ...DROP_II,
    dropSoldCount: 0,
    customNameAvailable: true,
    customNumberAvailable: true,
    customizationPriceCents: CUSTOMIZATION_PRICE,
  },

  // ── Casual Shirt Collection ─────────────────────────────────
  {
    id: "20000000-0000-4000-8000-000000000001",
    name: "PORTUGOOOL Brush Script Tee",
    slug: "brush-script-tee",
    description:
      "The brand name in one loud stroke. Soft, heavy, and easy to live in.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/brush-script-tee.webp", alt: "PORTUGOOOL Brush Script Tee · front" },
      { src: "/products/brush-script-tee-back.webp", alt: "PORTUGOOOL Brush Script Tee · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000002",
    name: "GOOOOOOOL!!! Tee",
    slug: "goool-tee",
    description:
      "The whole moment in one word. Wear the celebration.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "Deep Red",
    colorHex: "#C1121F",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/goool-tee.webp", alt: "GOOOOOOOL!!! Tee · front" },
      { src: "/products/goool-tee-back.webp", alt: "GOOOOOOOL!!! Tee · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000003",
    name: "Vamos Portugooool Tee",
    slug: "vamos-tee",
    description:
      "For the ones who start the chant. Soft-touch blend built for watch parties.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "Emerald Green",
    colorHex: "#0B3D2E",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/vamos-tee.webp", alt: "Vamos Portugooool Tee · front" },
      { src: "/products/vamos-tee-back.webp", alt: "Vamos Portugooool Tee · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000004",
    name: "From Lisbon to the World Tee",
    slug: "lisbon-to-the-world-tee",
    description:
      "One city, every living room, every corner bar. This one travels.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/lisbon-to-the-world-tee.webp", alt: "From Lisbon to the World Tee · front" },
      { src: "/products/lisbon-to-the-world-tee-back.webp", alt: "From Lisbon to the World Tee · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000005",
    name: "Match Day Tee",
    slug: "match-day-tee",
    description:
      "Some days are just different. Dress accordingly.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "Smoke Grey",
    colorHex: "#9CA3AF",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/match-day-tee.webp", alt: "Match Day Tee · front" },
      { src: "/products/match-day-tee-back.webp", alt: "Match Day Tee · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000006",
    name: "We Don't Whisper Goals Tee",
    slug: "we-dont-whisper-goals-tee",
    description:
      "Heavyweight, oversized, and honest about who you are during a match.",
    priceCents: 3300,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: HEAVY_FABRIC,
    fit: OVERSIZED_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/we-dont-whisper-goals-tee.webp", alt: "We Don't Whisper Goals Tee · front" },
      { src: "/products/we-dont-whisper-goals-tee-back.webp", alt: "We Don't Whisper Goals Tee · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },


  // == England Collection casual tees (Drop 02) ===============
  {
    id: "20000000-0000-4000-8000-000000000007",
    name: "ENGOOOLAND Echo Hero Tee",
    slug: "engoooland-echo-hero-tee",
    description:
      "The Echo, oversized, in red and navy. Chapter two on a clean white staple.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/engoooland-echo-hero-tee.webp", alt: "ENGOOOLAND Echo Hero Tee · front" },
      { src: "/products/engoooland-echo-hero-tee-back.webp", alt: "ENGOOOLAND Echo Hero Tee · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000008",
    name: "From London to the World Tee",
    slug: "london-to-the-world-tee",
    description:
      "One city, every corner bar. The London mirror of a Lisbon classic.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "England Navy",
    colorHex: "#0A1F3C",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/london-to-the-world-tee.webp", alt: "From London to the World Tee · front" },
      { src: "/products/london-to-the-world-tee-back.webp", alt: "From London to the World Tee · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000009",
    name: "Made for the Moment Tee",
    slug: "made-for-the-moment-tee",
    description:
      "The tagline, front and center. Deep red, built for the second it goes in.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "Deep Red",
    colorHex: "#C1121F",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/made-for-the-moment-tee.webp", alt: "Made for the Moment Tee · front" },
      { src: "/products/made-for-the-moment-tee-back.webp", alt: "Made for the Moment Tee · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "20000000-0000-4000-8000-000000000010",
    name: "ENGOOOLAND Roar Tee",
    slug: "engoooland-roar-tee",
    description:
      "Echo badge at the breast, the moment stacked beneath. Navy, understated, ready.",
    priceCents: 2300,
    compareAtPriceCents: null,
    color: "England Navy",
    colorHex: "#0A1F3C",
    fabric: CASUAL_FABRIC,
    fit: CASUAL_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/engoooland-roar-tee.webp", alt: "ENGOOOLAND Roar Tee · front" },
      { src: "/products/engoooland-roar-tee-back.webp", alt: "ENGOOOLAND Roar Tee · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },


  // == GOL House Line - performance tees (Printify/SwiftPOD) ==
  {
    id: "40000000-0000-4000-8000-000000000007",
    name: "GOL Clean Sheet Tee",
    slug: "gol-clean-sheet-tee",
    description:
      "The mark in ink on clean white. Performance fabric, daylight energy.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: PERF_FABRIC,
    fit: PERF_FIT,
    careInstructions: PERF_CARE,
    images: [
      { src: "/products/gol-clean-sheet-tee.webp", alt: "GOL Clean Sheet Tee · front" },
      { src: "/products/gol-clean-sheet-tee-alt.webp", alt: "GOL Clean Sheet Tee · detail" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printify",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "40000000-0000-4000-8000-000000000008",
    name: "GOL Gold Standard Tee",
    slug: "gol-gold-standard-tee",
    description:
      "Gold on black with a tonal slash. The house look, built to move.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: PERF_FABRIC,
    fit: PERF_FIT,
    careInstructions: PERF_CARE,
    images: [
      { src: "/products/gol-gold-standard-tee.webp", alt: "GOL Gold Standard Tee · front" },
      { src: "/products/gol-gold-standard-tee-alt.webp", alt: "GOL Gold Standard Tee · detail" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printify",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "40000000-0000-4000-8000-000000000009",
    name: "GOL Concrete Tee",
    slug: "gol-concrete-grey-tee",
    description:
      "The slash oversized, the mark up top. Street energy on performance poly.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Sport Grey",
    colorHex: "#9CA3AF",
    fabric: PERF_FABRIC,
    fit: PERF_FIT,
    careInstructions: PERF_CARE,
    images: [
      { src: "/products/gol-concrete-grey-tee.webp", alt: "GOL Concrete Tee · front" },
      { src: "/products/gol-concrete-grey-tee-alt.webp", alt: "GOL Concrete Tee · detail" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printify",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "40000000-0000-4000-8000-000000000010",
    name: "GOL Concrete White Tee",
    slug: "gol-concrete-white-tee",
    description:
      "Ink slash shoulder to hip, gold lockup. The loud one in white.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: PERF_FABRIC,
    fit: PERF_FIT,
    careInstructions: PERF_CARE,
    images: [
      { src: "/products/gol-concrete-white-tee.webp", alt: "GOL Concrete White Tee · front" },
      { src: "/products/gol-concrete-white-tee-alt.webp", alt: "GOL Concrete White Tee · detail" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printify",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "40000000-0000-4000-8000-000000000011",
    name: "GOL Concrete Black Tee",
    slug: "gol-concrete-black-tee",
    description:
      "Paper slash, gold mark. Blackout energy for the performance line.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: PERF_FABRIC,
    fit: PERF_FIT,
    careInstructions: PERF_CARE,
    images: [
      { src: "/products/gol-concrete-black-tee.webp", alt: "GOL Concrete Black Tee · front" },
      { src: "/products/gol-concrete-black-tee-alt.webp", alt: "GOL Concrete Black Tee · detail" },
    ],
    sizes: SHIRT_SIZES,
    category: "casual",
    supplierType: "printify",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },

  // ── Crest V2 T-Shirt Line (AA 1301GD, Printful DTF) ─────────
  {
    id: "60000000-0000-4000-8000-000000000003",
    name: "GOOOL Crest Statement Tee · Cream",
    slug: "crest-statement-tee-cream",
    description:
      "The crest at full volume. One design, worn loud on cream.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Faded Cream",
    colorHex: "#FFF9E9",
    fabric: HEAVY_FABRIC,
    fit: OVERSIZED_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/crest-statement-tee-cream.webp", alt: "GOOOL Crest Statement Tee · Cream · front" },
      { src: "/products/crest-statement-tee-cream-back.webp", alt: "GOOOL Crest Statement Tee · Cream · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "tshirt",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "60000000-0000-4000-8000-000000000004",
    name: "GOOOL Crest Statement Tee · Faded Black",
    slug: "crest-statement-tee-faded-black",
    description:
      "The crest at full volume, reversed in white on faded black.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Faded Black",
    colorHex: "#55565A",
    fabric: HEAVY_FABRIC,
    fit: OVERSIZED_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/crest-statement-tee-faded-black.webp", alt: "GOOOL Crest Statement Tee · Faded Black · front" },
      { src: "/products/crest-statement-tee-faded-black-back.webp", alt: "GOOOL Crest Statement Tee · Faded Black · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "tshirt",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "60000000-0000-4000-8000-000000000005",
    name: "GOOOL Crest Statement Tee · Faded Navy",
    slug: "crest-statement-tee-faded-navy",
    description:
      "The crest at full volume on dusty navy. The quiet-loud one.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Faded Navy",
    colorHex: "#4F5C71",
    fabric: HEAVY_FABRIC,
    fit: OVERSIZED_FIT,
    careInstructions: CASUAL_CARE,
    images: [
      { src: "/products/crest-statement-tee-faded-navy.webp", alt: "GOOOL Crest Statement Tee · Faded Navy · front" },
      { src: "/products/crest-statement-tee-faded-navy-back.webp", alt: "GOOOL Crest Statement Tee · Faded Navy · back" },
    ],
    sizes: SHIRT_SIZES,
    category: "tshirt",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },

  // ── GOOOL Oval Mark Oversized Tee (AS Colour 5082, Printful DTF) ──
  {
    id: "60000000-0000-4000-8000-000000000007",
    name: "GOOOL Oval Mark Oversized Tee",
    slug: "goool-oval-tee",
    description:
      "The GOOOL Oval Mark Oversized Tee brings professional football identity into a heavyweight streetwear silhouette. Made from garment dyed cotton with a structured boxy fit, dropped shoulders, and wide neck ribbing, it is designed to feel substantial while maintaining an easy everyday drape. The front carries the GOOOL oval wordmark, while a smaller G mark sits beneath the back collar like the finishing detail on a professional training kit.",
    priceCents: 3800,
    compareAtPriceCents: null,
    color: "Faded Cream",
    colorHex: "#FFF9E9",
    fabric:
      "100% carded cotton. Heavyweight 240 GSM (7.1 oz) fabric. Garment dyed and preshrunk.",
    fit: "Boxy oversized fit with dropped shoulders, wide sleeves, and wide neck ribbing. Longer casual length.",
    careInstructions:
      "Machine wash cold and inside out on a gentle cycle with mild detergent, with similar colors. Non-chlorine bleach only when necessary. No fabric softener. Tumble dry low or hang dry. Cool iron inside out when necessary · never directly over the decoration. Do not dry clean.",
    images: [
      { src: "/products/goool-oval-tee-cream.webp", alt: "GOOOL faded cream oversized t-shirt front view" },
      { src: "/products/goool-oval-tee-cream-back.webp", alt: "GOOOL faded cream oversized t-shirt back view" },
    ],
    sizes: OVERSIZED_TEE_SIZES,
    category: "tshirt",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
    colorVariants: [
      {
        name: "Faded Cream",
        supplierColor: "Faded Bone",
        hex: "#FFF9E9",
        skuFragment: "CREAM",
        images: [
          { src: "/products/goool-oval-tee-cream.webp", alt: "GOOOL faded cream oversized t-shirt front view" },
          { src: "/products/goool-oval-tee-cream-back.webp", alt: "GOOOL faded cream oversized t-shirt back view" },
          { src: "/products/goool-oval-tee-cream-detail-fit.webp", alt: "Oversized boxy fit detail, faded cream tee" },
          { src: "/products/goool-oval-tee-cream-detail-collar.webp", alt: "Wide neck ribbing and fabric detail, faded cream tee" },
        ],
      },
      {
        name: "Washed Charcoal",
        supplierColor: "Faded Black",
        hex: "#55565A",
        skuFragment: "CHARCOAL",
        images: [
          { src: "/products/goool-oval-tee-charcoal.webp", alt: "GOOOL washed charcoal oversized t-shirt front view" },
          { src: "/products/goool-oval-tee-charcoal-back.webp", alt: "GOOOL washed charcoal oversized t-shirt back view" },
          { src: "/products/goool-oval-tee-charcoal-detail-fit.webp", alt: "Oversized boxy fit detail, washed charcoal tee" },
          { src: "/products/goool-oval-tee-charcoal-detail-collar.webp", alt: "Wide neck ribbing and fabric detail, washed charcoal tee" },
        ],
      },
      {
        name: "Dusty Navy",
        supplierColor: "Faded Indigo",
        hex: "#4F5C71",
        skuFragment: "NAVY",
        images: [
          { src: "/products/goool-oval-tee-navy.webp", alt: "GOOOL dusty navy oversized t-shirt front view" },
          { src: "/products/goool-oval-tee-navy-back.webp", alt: "GOOOL dusty navy oversized t-shirt back view" },
          { src: "/products/goool-oval-tee-navy-detail-fit.webp", alt: "Oversized boxy fit detail, dusty navy tee" },
          { src: "/products/goool-oval-tee-navy-detail-collar.webp", alt: "Wide neck ribbing and fabric detail, dusty navy tee" },
        ],
      },
    ],
    fitNote:
      "Boxy oversized fit with dropped shoulders. Choose your normal size for the intended oversized silhouette. Size down for a closer fit.",
    sizeGuide: {
      unit: "in",
      measurements: [
        { label: "Length", values: { S: 27.76, M: 29.13, L: 30.51, XL: 31.89, XXL: 33.27 } },
        { label: "Width", values: { S: 20.08, M: 21.65, L: 23.23, XL: 24.8, XXL: 26.38 } },
        { label: "Sleeve Length", values: { S: 9.06, M: 9.45, L: 9.45, XL: 10.24, XXL: 10.63 } },
      ],
    },
  },

  // ── Accessory Collection ────────────────────────────────────
  {
    id: "30000000-0000-4000-8000-000000000001",
    name: "Supporters Scarf",
    slug: "supporters-scarf",
    description:
      "Double-sided knit scarf. Raise it at kickoff, wear it home after.",
    priceCents: 2800,
    compareAtPriceCents: null,
    color: "Red / Green",
    colorHex: "#C1121F",
    fabric: "Double-sided acrylic knit with fringed ends. Stadium-weight.",
    fit: "One size · 145 × 18 cm.",
    careInstructions: ACCESSORY_CARE,
    images: [
      { src: "/products/supporters-scarf.svg", alt: "Supporters Scarf" },
    ],
    sizes: ONE_SIZE,
    category: "accessory",
    supplierType: "unassigned",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "30000000-0000-4000-8000-000000000002",
    name: "GOOOOOL Cap",
    slug: "goool-cap",
    description:
      "Low-profile cap with the sound of victory stitched on the front.",
    priceCents: 2900,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "Brushed cotton twill, embroidered front, adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: ACCESSORY_CARE,
    images: [{ src: "/products/goool-cap.svg", alt: "GOOOOOL Cap" }],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "30000000-0000-4000-8000-000000000003",
    name: "Sticker Pack",
    slug: "sticker-pack",
    description:
      "Six die-cut stickers. Laptops, bottles, and anything else that needs more noise.",
    priceCents: 1000,
    compareAtPriceCents: null,
    color: "Multi",
    colorHex: "#C9A227",
    fabric: "Kiss-cut matte vinyl sticker sheet. Six designs on one sheet.",
    fit: "One sheet · 5.83″ × 8.27″ · six stickers.",
    careInstructions: "Peel and place once.",
    images: [{ src: "/products/sticker-pack.svg", alt: "Sticker Pack · six die-cut stickers" }],
    sizes: ONE_SIZE,
    category: "accessory",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "30000000-0000-4000-8000-000000000004",
    name: "Terrace Flag",
    slug: "terrace-flag",
    description:
      "90 × 150 cm of pure celebration. For balconies, backyards, and full-time whistles.",
    priceCents: 2400,
    compareAtPriceCents: null,
    color: "Red / Green / Gold",
    colorHex: "#0B3D2E",
    fabric: "Lightweight knitted polyester with reinforced grommets.",
    fit: "One size · 90 × 150 cm.",
    careInstructions: ACCESSORY_CARE,
    images: [{ src: "/products/terrace-flag.svg", alt: "Terrace Flag" }],
    sizes: ONE_SIZE,
    category: "accessory",
    supplierType: "unassigned",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },

  // == GOL caps (Printful embroidery, Yupoong 6245CM) =========
  {
    id: "50000000-0000-4000-8000-000000000001",
    name: "GOL Cap Black",
    slug: "gol-cap-black",
    description:
      "Gold GOL, stitched. Low-profile classic cap, adjustable strap.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "Brushed cotton twill, embroidered GOL mark, adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/gol-cap-black.webp", alt: "GOL Cap Black · front" },
      { src: "/products/gol-cap-black-alt.webp", alt: "GOL Cap Black · angle" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000002",
    name: "GOL Cap White",
    slug: "gol-cap-white",
    description:
      "Ink GOL, stitched clean on white. Low-profile classic cap, adjustable strap.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: "Brushed cotton twill, embroidered GOL mark, adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/gol-cap-white.webp", alt: "GOL Cap White · front" },
      { src: "/products/gol-cap-white-alt.webp", alt: "GOL Cap White · angle" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000003",
    name: "GOOOL Cap Black",
    slug: "goool-cap-black",
    description:
      "The house wordmark in gold thread. The Sound of Victory. on the side.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "Brushed cotton twill, embroidered GOOOL wordmark, adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-cap-black.webp", alt: "GOOOL Cap Black · front angle" },
      { src: "/products/goool-cap-black-alt.webp", alt: "GOOOL Cap Black · front" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000004",
    name: "GOOOL Cap White",
    slug: "goool-cap-white",
    description:
      "GOOOL stitched in ink on white. The Sound of Victory. on the side.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: "Brushed cotton twill, embroidered GOOOL wordmark, adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-cap-white.webp", alt: "GOOOL Cap White · front angle" },
      { src: "/products/goool-cap-white-alt.webp", alt: "GOOOL Cap White · front" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000005",
    name: "GOOOL England Cap",
    slug: "goool-england-cap",
    description:
      "Red, white, and navy. GOOOL in navy thread, England in red, the cross on the shield. Part of The England Drop.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Red / White",
    colorHex: "#C1121F",
    fabric: "Structured 5-panel trucker, embroidered front panel, mesh back, snapback.",
    fit: "One size · snapback.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-england-cap.webp", alt: "GOOOL England Cap · front" },
      { src: "/products/goool-england-cap-alt.webp", alt: "GOOOL England Cap · angle" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000006",
    name: "GOOOL England Cap White",
    slug: "goool-england-cap-white",
    description:
      "White crown, navy GOOOL, England red. The cross on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-england-cap-white.webp", alt: "GOOOL England Cap White · front" },
      { src: "/products/goool-england-cap-white-alt.webp", alt: "GOOOL England Cap White · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000007",
    name: "GOOOL England Cap Navy",
    slug: "goool-england-cap-navy",
    description:
      "England navy, white GOOOL, red England. The cross on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Navy",
    colorHex: "#0A1F3C",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-england-cap-navy.webp", alt: "GOOOL England Cap Navy · front" },
      { src: "/products/goool-england-cap-navy-alt.webp", alt: "GOOOL England Cap Navy · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000008",
    name: "GOOOL England Cap Red",
    slug: "goool-england-cap-red",
    description:
      "Deep red, white GOOOL. The cross on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Red",
    colorHex: "#9E1B32",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-england-cap-red.webp", alt: "GOOOL England Cap Red · front" },
      { src: "/products/goool-england-cap-red-alt.webp", alt: "GOOOL England Cap Red · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: "II",
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000009",
    name: "GOOOL Argentina Cap White",
    slug: "goool-argentina-cap-white",
    description:
      "White crown, navy GOOOL, celeste Argentina. The flag shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-argentina-cap-white.webp", alt: "GOOOL Argentina Cap White · front" },
      { src: "/products/goool-argentina-cap-white-alt.webp", alt: "GOOOL Argentina Cap White · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000010",
    name: "GOOOL Argentina Cap Sky Blue",
    slug: "goool-argentina-cap-sky",
    description:
      "Celeste, white GOOOL. The flag shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Sky Blue",
    colorHex: "#75AADB",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-argentina-cap-sky.webp", alt: "GOOOL Argentina Cap Sky Blue · front" },
      { src: "/products/goool-argentina-cap-sky-alt.webp", alt: "GOOOL Argentina Cap Sky Blue · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },

  // == Country caps wave 2 (Yupoong 6245CM via Printful) ======
  {
    id: "50000000-0000-4000-8000-000000000011",
    name: "GOOOL Italy Cap Navy",
    slug: "goool-italy-cap-navy",
    description:
      "Azzurri navy, white GOOOL, green Italy. The tricolore shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Navy",
    colorHex: "#0A1F3C",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-italy-cap-navy.webp", alt: "GOOOL Italy Cap Navy · front" },
      { src: "/products/goool-italy-cap-navy-alt.webp", alt: "GOOOL Italy Cap Navy · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000012",
    name: "GOOOL Italy Cap White",
    slug: "goool-italy-cap-white",
    description:
      "White crown, navy GOOOL, green Italy. The tricolore shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-italy-cap-white.webp", alt: "GOOOL Italy Cap White · front" },
      { src: "/products/goool-italy-cap-white-alt.webp", alt: "GOOOL Italy Cap White · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000013",
    name: "GOOOL Netherlands Cap Navy",
    slug: "goool-netherlands-cap-navy",
    description:
      "Navy crown, white GOOOL, Oranje accent. The flag shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Navy",
    colorHex: "#0A1F3C",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-netherlands-cap-navy.webp", alt: "GOOOL Netherlands Cap Navy · front" },
      { src: "/products/goool-netherlands-cap-navy-alt.webp", alt: "GOOOL Netherlands Cap Navy · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000024",
    name: "GOOOL Netherlands Cap White",
    slug: "goool-netherlands-cap-white",
    description:
      "White crown, navy GOOOL, Oranje accent. The flag shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-netherlands-cap-white.webp", alt: "GOOOL Netherlands Cap White · front" },
      { src: "/products/goool-netherlands-cap-white-alt.webp", alt: "GOOOL Netherlands Cap White · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000014",
    name: "GOOOL Germany Cap Black",
    slug: "goool-germany-cap-black",
    description:
      "Black crown, white GOOOL, red Germany. The flag shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-germany-cap-black.webp", alt: "GOOOL Germany Cap Black · front" },
      { src: "/products/goool-germany-cap-black-alt.webp", alt: "GOOOL Germany Cap Black · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000015",
    name: "GOOOL Germany Cap White",
    slug: "goool-germany-cap-white",
    description:
      "White crown, black GOOOL, red Germany. The flag shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-germany-cap-white.webp", alt: "GOOOL Germany Cap White · front" },
      { src: "/products/goool-germany-cap-white-alt.webp", alt: "GOOOL Germany Cap White · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000016",
    name: "GOOOL Belgium Cap Red",
    slug: "goool-belgium-cap-red",
    description:
      "Deep red, gold GOOOL, black Belgium. The flag shield on the side, gold GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Red",
    colorHex: "#9E1B32",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-belgium-cap-red.webp", alt: "GOOOL Belgium Cap Red · front" },
      { src: "/products/goool-belgium-cap-red-alt.webp", alt: "GOOOL Belgium Cap Red · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000017",
    name: "GOOOL Belgium Cap Black",
    slug: "goool-belgium-cap-black",
    description:
      "Black crown, gold GOOOL, red Belgium. The flag shield on the side, gold GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-belgium-cap-black.webp", alt: "GOOOL Belgium Cap Black · front" },
      { src: "/products/goool-belgium-cap-black-alt.webp", alt: "GOOOL Belgium Cap Black · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000018",
    name: "GOOOL Norway Cap Navy",
    slug: "goool-norway-cap-navy",
    description:
      "Navy crown, white GOOOL, red Norway. The Nordic cross shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Navy",
    colorHex: "#0A1F3C",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-norway-cap-navy.webp", alt: "GOOOL Norway Cap Navy · front" },
      { src: "/products/goool-norway-cap-navy-alt.webp", alt: "GOOOL Norway Cap Navy · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000019",
    name: "GOOOL Norway Cap Red",
    slug: "goool-norway-cap-red",
    description:
      "Deep red, white GOOOL. The Nordic cross shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Red",
    colorHex: "#9E1B32",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-norway-cap-red.webp", alt: "GOOOL Norway Cap Red · front" },
      { src: "/products/goool-norway-cap-red-alt.webp", alt: "GOOOL Norway Cap Red · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000020",
    name: "GOOOL Spain Cap Black",
    slug: "goool-spain-cap-black",
    description:
      "Black crown, gold GOOOL, red Spain. The rojigualda shield on the side, gold GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-spain-cap-black.webp", alt: "GOOOL Spain Cap Black · front" },
      { src: "/products/goool-spain-cap-black-alt.webp", alt: "GOOOL Spain Cap Black · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000021",
    name: "GOOOL Spain Cap Red",
    slug: "goool-spain-cap-red",
    description:
      "Deep red, gold GOOOL. The rojigualda shield on the side, gold GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Red",
    colorHex: "#9E1B32",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-spain-cap-red.webp", alt: "GOOOL Spain Cap Red · front" },
      { src: "/products/goool-spain-cap-red-alt.webp", alt: "GOOOL Spain Cap Red · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000022",
    name: "GOOOL France Cap Navy",
    slug: "goool-france-cap-navy",
    description:
      "Navy crown, white GOOOL, red France. The tricolore shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "Navy",
    colorHex: "#0A1F3C",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-france-cap-navy.webp", alt: "GOOOL France Cap Navy · front" },
      { src: "/products/goool-france-cap-navy-alt.webp", alt: "GOOOL France Cap Navy · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "50000000-0000-4000-8000-000000000023",
    name: "GOOOL France Cap White",
    slug: "goool-france-cap-white",
    description:
      "White crown, navy GOOOL, red France. The tricolore shield on the side, GOOOL on the back.",
    priceCents: 3500,
    compareAtPriceCents: null,
    color: "White",
    colorHex: "#FFFFFF",
    fabric: "Brushed cotton twill, embroidered front, side crest, and back mark. Adjustable strap.",
    fit: "One size · adjustable.",
    careInstructions: "Spot clean or hand wash cold. Lay flat to dry.",
    images: [
      { src: "/products/goool-france-cap-white.webp", alt: "GOOOL France Cap White · front" },
      { src: "/products/goool-france-cap-white-alt.webp", alt: "GOOOL France Cap White · side crest" },
    ],
    sizes: ONE_SIZE,
    category: "hat",
    supplierType: "printful",
    isActive: false,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },

  // == First Capsule (Apliiq; Coming Soon - sample approval pending) ==
  {
    id: "70000000-0000-4000-8000-000000000001",
    name: "GOOOL Performance Badge Tee",
    slug: "goool-performance-tee",
    description:
      "Lightweight training tee. GOOOL crest centered on the chest, athletic fit, taped neck.",
    priceCents: 4800,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "3.8 oz 100% recycled polyester with PosiCharge.",
    fit: "Athletic fit. True to size.",
    careInstructions: "Machine wash cold. Tumble dry low. Do not iron the print.",
    images: [
      {
        src: "/products/GOOOL_STD_PERFORMANCE_BLACK_FRONT.webp",
        alt: "GOOOL Performance Badge Tee in black, front view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
      {
        src: "/products/GOOOL_STD_PERFORMANCE_BLACK_BACK.webp",
        alt: "GOOOL Performance Badge Tee in black, back view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
    ],
    // Colorways mirror the saved Apliiq designs
    // (Black 6098962, White 6099046, True Royal 6099129).
    colorVariants: [
      {
        name: "Black",
        supplierColor: "Black",
        hex: "#373737",
        skuFragment: "BLACK",
        images: [
          {
            src: "/products/GOOOL_STD_PERFORMANCE_BLACK_FRONT.webp",
            alt: "GOOOL Performance Badge Tee in black, front view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_STD_PERFORMANCE_BLACK_BACK.webp",
            alt: "GOOOL Performance Badge Tee in black, back view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
      {
        name: "White",
        supplierColor: "White",
        hex: "#F4F4F4",
        skuFragment: "WHITE",
        images: [
          {
            src: "/products/GOOOL_STD_PERFORMANCE_WHITE_FRONT.webp",
            alt: "GOOOL Performance Badge Tee in white, front view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_STD_PERFORMANCE_WHITE_BACK.webp",
            alt: "GOOOL Performance Badge Tee in white, back view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
      {
        name: "True Royal",
        supplierColor: "true royal",
        hex: "#3249A6",
        skuFragment: "TRUE_ROYAL",
        images: [
          {
            src: "/products/GOOOL_STD_PERFORMANCE_ROYAL_FRONT.webp",
            alt: "GOOOL Performance Badge Tee in true royal, front view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_STD_PERFORMANCE_ROYAL_BACK.webp",
            alt: "GOOOL Performance Badge Tee in true royal, back view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
    ],
    // Garment made in Ethiopia (Apliiq record); decorated at Apliiq's US
    // facilities (LA/Philadelphia) - so Printed in the USA, never Made in.
    originLabel: "Printed in the USA",
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "tshirt",
    supplierType: "apliiq",
    isActive: true,
    availableForSale: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "70000000-0000-4000-8000-000000000002",
    name: "GOOOL Core Hoodie",
    slug: "goool-heavyweight-hoodie",
    description:
      "Heavyweight pullover hoodie. Underlined GOOOL wordmark across the chest, kangaroo pocket, generous fit.",
    priceCents: 7800,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "10 oz (330 gsm) 3-end fleece, 70/30 cotton-poly with 100% cotton face yarn.",
    fit: "Generous, relaxed fit.",
    careInstructions: "Machine wash cold. Tumble dry low. Do not iron the print.",
    images: [
      {
        src: "/products/GOOOL_STD_HOODIE_BLACK_FRONT.webp",
        alt: "GOOOL Core Hoodie in black, front view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
      {
        src: "/products/GOOOL_STD_HOODIE_BLACK_BACK.webp",
        alt: "GOOOL Core Hoodie in black, back view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
    ],
    // Colorways mirror the saved Apliiq designs (Black 6098974, Bone 6099064).
    colorVariants: [
      {
        name: "Black",
        supplierColor: "Black",
        hex: "#1E1E1E",
        skuFragment: "BLACK",
        images: [
          {
            src: "/products/GOOOL_STD_HOODIE_BLACK_FRONT.webp",
            alt: "GOOOL Core Hoodie in black, front view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_STD_HOODIE_BLACK_BACK.webp",
            alt: "GOOOL Core Hoodie in black, back view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
      {
        name: "Bone",
        supplierColor: "Bone",
        hex: "#CFCAC7",
        skuFragment: "BONE",
        images: [
          {
            src: "/products/GOOOL_STD_HOODIE_BONE_FRONT.webp",
            alt: "GOOOL Core Hoodie in bone, front view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_STD_HOODIE_BONE_BACK.webp",
            alt: "GOOOL Core Hoodie in bone, back view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
    ],
    // Garment made in China (Apliiq record); decorated at Apliiq's US
    // facilities (LA/Philadelphia) - so Printed in the USA, never Made in.
    originLabel: "Printed in the USA",
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "hoodie",
    supplierType: "apliiq",
    isActive: true,
    availableForSale: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "70000000-0000-4000-8000-000000000003",
    name: "GOOOL Casual Wordmark Tee",
    slug: "goool-heavyweight-casual-tee",
    description:
      "Garment-dyed heavyweight cotton tee. Underlined GOOOL wordmark across the chest, relaxed fit, semi-dropped shoulder.",
    priceCents: 4800,
    compareAtPriceCents: null,
    color: "Washed Black",
    colorHex: "#2E2E30",
    fabric: "6.5 oz 100% ring-spun cotton, garment-dyed.",
    fit: "Relaxed heavyweight fit, semi-dropped shoulder.",
    careInstructions: "Machine wash cold with like colors. Tumble dry low.",
    images: [
      {
        src: "/products/GOOOL_STD_CASUAL_WASHED_BLACK_FRONT.webp",
        alt: "GOOOL Casual Wordmark Tee in washed black, front view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
      {
        src: "/products/GOOOL_STD_CASUAL_WASHED_BLACK_BACK.webp",
        alt: "GOOOL Casual Wordmark Tee in washed black, back view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
    ],
    // Colorways mirror the saved Apliiq designs (Washed Black 6113934, Washed Grey
    // 6113938) - front print at 10in wide, rebuilt from a native 3000px master
    // 2026-09-21 (was 6.75in / 6098963 + 6099060, now superseded). Back stays
    // blank on both colors; Apliiq never had a back print for this product.
    colorVariants: [
      {
        name: "Washed Black",
        supplierColor: "Washed Black",
        hex: "#262626",
        skuFragment: "WBLACK",
        images: [
          {
            src: "/products/GOOOL_STD_CASUAL_WASHED_BLACK_FRONT.webp",
            alt: "GOOOL Casual Wordmark Tee in washed black, front view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_STD_CASUAL_WASHED_BLACK_BACK.webp",
            alt: "GOOOL Casual Wordmark Tee in washed black, back view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
      {
        name: "Washed Grey",
        supplierColor: "Washed Grey",
        hex: "#7D7D7B",
        skuFragment: "WGREY",
        images: [
          {
            src: "/products/GOOOL_STD_CASUAL_WASHED_GREY_FRONT.webp",
            alt: "GOOOL Casual Wordmark Tee in washed grey, front view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_STD_CASUAL_WASHED_GREY_BACK.webp",
            alt: "GOOOL Casual Wordmark Tee in washed grey, back view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
    ],
    // Garment made in Nicaragua (Apliiq record); decorated at Apliiq's US
    // facilities (LA/Philadelphia) - so Printed in the USA, never Made in.
    originLabel: "Printed in the USA",
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "tshirt",
    supplierType: "apliiq",
    isActive: true,
    availableForSale: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },
  {
    id: "70000000-0000-4000-8000-000000000004",
    name: "GOOOL Touchline Cap",
    slug: "goool-touchline-cap",
    description:
      "Structured five-panel cap in black and natural. Flat-embroidered GOOOL wordmark on the front panel, curved visor, adjustable snap.",
    // $48, not $36: the embroidered cap costs $29.88/unit on Apliiq's dropship
    // rate (blank $14.06 + flat embroidery), the highest decoration cost in the
    // catalog. At $36 that was a 17% margin - the only product under the floor.
    // $48 puts it at 38% without depending on the VIP subscription.
    priceCents: 4800,
    compareAtPriceCents: null,
    color: "Black/Natural",
    colorHex: "#E4DFC9",
    fabric: "65/35 polyester-cotton twill with firm buckram front.",
    fit: "Adjustable - One Size. Structured mid-profile crown.",
    careInstructions: "Spot clean only.",
    images: [
      {
        src: "/products/GOOOL_STD_TOUCHLINE_CAP_FRONT.webp",
        alt: "GOOOL Touchline Cap in black and natural, front view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
      {
        src: "/products/GOOOL_STD_TOUCHLINE_CAP_BACK.webp",
        alt: "GOOOL Touchline Cap in black and natural, back view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
    ],
    sizes: ["OS"],
    category: "hat",
    supplierType: "apliiq",
    isActive: true,
    availableForSale: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
  },

  // == GOOOL Athletics (Coming Soon; owner-authorized 30% modeled margin) ==
  // Cost model: designs/18_launch_operations/PRICING-25-PERCENT.json.
  // The MODEL in that file is still the authority (2.9% + $0.30 card
  // fee, 5% reprint reserve, $3 label budget, $1/item fulfillment, size
  // surcharge on the worst size). Its PRICES are superseded: the owner
  // raised the floor from 25% to 30% of the worst-size landed cost on
  // 2026-09-22 and every product was recomputed against fresh Apliiq
  // dropship quotes read that day. Price = lowest value ending in 8 at
  // or above (landed + 0.30) / 0.621.
  //
  // The single biggest lever here is the $3 label budget, which that
  // file itself flags as an unverified contingency. It is ~8 points on
  // a $38 tee. Drop the label program and the floors fall roughly one
  // step: crewneck $98, performance tee $48, badge tee $38.
  // Cotton Modern Sport is archived for a performance-only launch.
  // Saved-design garment/print costs are verified; labeling, shipping and
  // sample approval remain launch gates. Pricing does not authorize sales.
  // Keep supplierType unassigned and availableForSale false until readiness
  // is verified. Gallery images remain disclosed concept renders.
  {
    id: "80000000-0000-4000-8000-000000000001",
    name: "GOOOL Athletics Modern Sport Tee",
    slug: "goool-athletics-modern-sport-tee",
    description:
      "Bold, forward-leaning GOOOL in white across the chest, a red underline, and widely spaced ATHLETICS beneath. Small white GOOOL Athletics mark at the upper back. Solid black crewneck.",
    // Archived (isActive false), but priced on the same basis as the
    // rest so it is correct if it is ever revived. The $64 it carried
    // until 2026-09-22 was never a considered price: this cotton
    // version was archived in favour of the ST720 performance twin, so
    // PRICING-25-PERCENT.json skips it and nothing ever repriced it.
    // Quote $24.48, worst-size landed $30.48, floor $49.57 -> $58.
    priceCents: 5800,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "Premium cotton crewneck tee, opaque, rib collar. Fabric weight and construction are confirmed at sample approval.",
    fit: "Relaxed body with a moderate dropped shoulder.",
    careInstructions: "Care instructions follow the approved blank and print process.",
    images: [
      {
        src: "/products/GOOOL_STD_MODERN_SPORT_FRONT.webp",
        alt: "GOOOL Athletics Modern Sport Tee in black, front view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
      {
        src: "/products/GOOOL_STD_MODERN_SPORT_BACK.webp",
        alt: "GOOOL Athletics Modern Sport Tee in black, back view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "tshirt",
    supplierType: "unassigned",
    isActive: false,
    availableForSale: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
    disclosure:
      "In development. Final garment and print details are being checked with the production partner. Product photography follows sample approval.",
  },
  {
    id: "80000000-0000-4000-8000-000000000002",
    name: "GOOOL Athletics Varsity Tee",
    slug: "goool-athletics-varsity-tee",
    description:
      "Garment-dyed washed black tee. Arched collegiate GOOOL in warm ivory with a dark red outline, ATHLETICS below between short rules, across the chest.",
    priceCents: 4800,
    compareAtPriceCents: null,
    color: "Washed Black",
    colorHex: "#262626",
    fabric: "Premium cotton crewneck tee, garment-dyed washed black, opaque, rib collar. Fabric weight and construction are confirmed at sample approval.",
    fit: "Relaxed body with a moderate dropped shoulder.",
    careInstructions: "Care instructions follow the approved blank and print process.",
    images: [
      {
        src: "/products/GOOOL_STD_VARSITY_FRONT.webp",
        alt: "GOOOL Athletics Varsity Tee in washed black, front view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
      {
        src: "/products/GOOOL_STD_VARSITY_BACK.webp",
        alt: "GOOOL Athletics Varsity Tee in washed black, back view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
    ],
    // Colorways mirror the saved Apliiq designs (Washed Black 6114178, Washed
    // Navy 6114196) - front print only, 12.5in GA-02-F (scaled up from 11in
    // 2026-09-21; 14in was tested and rejected for crowding the sleeve
    // seams). The back mark (GA-02-B) was dropped 2026-09-21: on this blank,
    // Back Box 1 starts too low to reach the site's concept placement, so
    // the owner chose to cut the back print rather than ship a mismatched
    // garment. 6112032 (front+back) and 6113914/6113912 (front-only, 11in)
    // are superseded and marked VOID in Apliiq.
    colorVariants: [
      {
        name: "Washed Black",
        supplierColor: "Washed Black",
        hex: "#262626",
        skuFragment: "WBLACK",
        images: [
          {
            src: "/products/GOOOL_STD_VARSITY_FRONT.webp",
            alt: "GOOOL Athletics Varsity Tee in washed black, front view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_STD_VARSITY_BACK.webp",
            alt: "GOOOL Athletics Varsity Tee in washed black, back view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
      {
        name: "Washed Navy",
        supplierColor: "Washed Navy",
        hex: "#414C67",
        skuFragment: "WNAVY",
        images: [
          {
            src: "/products/GOOOL_STD_VARSITY_WASHED_NAVY_FRONT.webp",
            alt: "GOOOL Athletics Varsity Tee in washed navy, front view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_STD_VARSITY_WASHED_NAVY_BACK.webp",
            alt: "GOOOL Athletics Varsity Tee in washed navy, back view",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "tshirt",
    supplierType: "unassigned",
    isActive: true,
    availableForSale: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
    disclosure:
      "In development. Final garment and print details are being checked with the production partner. Product photography follows sample approval.",
  },
  {
    id: "80000000-0000-4000-8000-000000000003",
    name: "GOOOL Athletics Minimal Club Tee",
    slug: "goool-athletics-minimal-club-tee",
    description:
      "Natural cream heavyweight tee. GOOOL Athletics badge at the left chest, full GOOOL ATHLETICS with a red underline across the upper back.",
    priceCents: 4800,
    compareAtPriceCents: null,
    color: "Natural",
    colorHex: "#E5E5DD",
    fabric: "Premium cotton crewneck tee, natural cream, opaque, rib collar. Fabric weight and construction are confirmed at sample approval.",
    fit: "Relaxed body with a moderate dropped shoulder.",
    careInstructions: "Care instructions follow the approved blank and print process.",
    images: [
      {
        src: "/products/GOOOL_STD_MINIMAL_CLUB_FRONT.webp",
        alt: "GOOOL Athletics Minimal Club Tee in natural cream, front view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
      {
        src: "/products/GOOOL_STD_MINIMAL_CLUB_BACK.webp",
        alt: "GOOOL Athletics Minimal Club Tee in natural cream, back view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "tshirt",
    supplierType: "unassigned",
    isActive: true,
    availableForSale: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
    disclosure:
      "In development. Final garment and print details are being checked with the production partner. Product photography follows sample approval.",
  },
  // Circular-logo family (designs/16_goool_athletics/circular_logo/,
  // 2026-09-20): twelve archived options; only GA-CIRCLE-08 and
  // GA-CIRCLE-09 were designated for the site. Both blanks are now
  // verified with the supplier: Comfort Colors C1717 Ivory, and AS
  // Colour 5150 Made Crew in Athletic Heather (that blank offers no
  // color literally named "gray heather"; Athletic Heather is its only
  // heather gray and the owner approved it on 2026-09-21, so the
  // "Gray Heather" strings below stay as descriptive site copy). The
  // priced, unpurchasable Coming Soon posture is unchanged: it waits
  // on physical sample approval, not on supplier mapping.
  {
    id: "80000000-0000-4000-8000-000000000004",
    name: "GOOOL Athletics Circular Badge Tee",
    slug: "goool-athletics-circular-badge-tee",
    description:
      "Ivory heavyweight tee. Navy circular GOOOL Athletics badge at the left chest, the letters themselves forming the ring.",
    priceCents: 4800,
    compareAtPriceCents: null,
    color: "Ivory",
    colorHex: "#E9E1D7",
    fabric: "Premium heavyweight cotton crewneck tee, ivory. Fabric weight and construction are confirmed at sample approval.",
    fit: "Relaxed body with a moderate dropped shoulder.",
    careInstructions: "Care instructions follow the approved blank and print process.",
    images: [
      {
        src: "/products/GOOOL_STD_CIRCULAR_BADGE_FRONT.webp",
        alt: "GOOOL Athletics Circular Badge Tee in ivory, front view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
      {
        src: "/products/GOOOL_STD_CIRCULAR_BADGE_BACK.webp",
        alt: "GOOOL Athletics Circular Badge Tee in ivory, back view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "tshirt",
    supplierType: "unassigned",
    isActive: true,
    availableForSale: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
    disclosure:
      "In development. Final garment and print details are being checked with the production partner. Product photography follows sample approval.",
  },
  {
    id: "80000000-0000-4000-8000-000000000005",
    name: "GOOOL Athletics Circular Center Crewneck",
    slug: "goool-athletics-circular-center-crewneck",
    description:
      "Gray heather French terry crewneck. Forest green circular GOOOL Athletics mark centered on the upper chest, the letters themselves forming the ring.",
    priceCents: 8800,
    compareAtPriceCents: null,
    color: "Gray Heather",
    colorHex: "#B2B2B2",
    fabric: "Premium heavyweight fleece crewneck, gray heather, rib collar, cuffs and hem. Fabric weight and construction are confirmed at sample approval.",
    fit: "Relaxed body with a moderate dropped shoulder.",
    careInstructions: "Care instructions follow the approved blank and print process.",
    images: [
      {
        src: "/products/GOOOL_STD_CIRCULAR_CREWNECK_FRONT.webp",
        alt: "GOOOL Athletics Circular Center Crewneck in gray heather, front view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
      {
        src: "/products/GOOOL_STD_CIRCULAR_CREWNECK_BACK.webp",
        alt: "GOOOL Athletics Circular Center Crewneck in gray heather, back view",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "hoodie",
    supplierType: "unassigned",
    isActive: true,
    availableForSale: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
    disclosure:
      "In development. Final garment and print details are being checked with the production partner. Product photography follows sample approval.",
  },
  // Modern Sport is performance-only for launch; cotton remains archived.
  // ST720 supplier design exists. All images remain concepts and sales
  // await actual-size print proof, sample and fulfillment readiness.
  {
    id: "80000000-0000-4000-8000-000000000006",
    name: "GOOOL Athletics Modern Sport Performance Tee",
    slug: "goool-athletics-modern-sport-performance-tee",
    description:
      "Performance training tee in black or true royal. White GOOOL with a red underline and spaced ATHLETICS across the chest, GOOOL Athletics mark at the upper back.",
    priceCents: 4800,
    compareAtPriceCents: null,
    color: "Black",
    colorHex: "#0A0A0A",
    fabric: "Performance polyester training tee. Fabric weight and construction are confirmed at sample approval.",
    fit: "Athletic fit. Confirmed at sample approval.",
    careInstructions: "Care instructions follow the approved blank and print process.",
    images: [
      {
        src: "/products/GOOOL_MODERN_PERFORMANCE_FRONT_V2.png",
        alt: "GOOOL Athletics Modern Sport Performance Tee in black, front view with the white GOOOL wordmark, red underline and ATHLETICS",
        caption: "Concept render. Not a photograph of a manufactured sample.",
      },
      {
        src: "/products/GOOOL_MODERN_PERFORMANCE_BACK_DETAIL_V2.png",
        alt: "Close-up concept of the Modern Sport Performance Tee's white upper-back GOOOL Athletics print",
        caption: "Back print detail - concept render. Not a photograph of a manufactured sample.",
      },
    ],
    // Second colourway approved by the owner 2026-09-21. True Royal is a
    // stock ST720 colour (Apliiq colour 371, #2e48b6) on the SAME blank as
    // Black, with the SAME artwork files at the same sizes, so the two
    // colourways differ only in garment colour.
    colorVariants: [
      {
        name: "Black",
        supplierColor: "Black",
        hex: "#373737",
        skuFragment: "BLACK",
        images: [
          {
            src: "/products/GOOOL_MODERN_PERFORMANCE_FRONT_V2.png",
            alt: "GOOOL Athletics Modern Sport Performance Tee in black, front view with the white GOOOL wordmark, red underline and ATHLETICS",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_MODERN_PERFORMANCE_BACK_DETAIL_V2.png",
            alt: "Close-up concept of the Modern Sport Performance Tee's white upper-back GOOOL Athletics print, black garment",
            caption: "Back print detail - concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
      {
        name: "True Royal",
        supplierColor: "true royal",
        // Sampled from Apliiq's OWN rendered garment for saved design
        // 6113361, not from their swatch hex. Their API reports the
        // swatch as #2E48B6, but the rendered garment body measures
        // #354CAA - softer and less saturated. The render is what
        // actually ships, so it governs both this swatch and the imagery.
        hex: "#354CAA",
        skuFragment: "ROYAL",
        images: [
          {
            src: "/products/GOOOL_MODERN_PERFORMANCE_ROYAL_FRONT.png",
            alt: "GOOOL Athletics Modern Sport Performance Tee in true royal blue, front view with the white GOOOL wordmark, red underline and ATHLETICS",
            caption: "Concept render. Not a photograph of a manufactured sample.",
          },
          {
            src: "/products/GOOOL_MODERN_PERFORMANCE_ROYAL_BACK_DETAIL.png",
            alt: "Close-up concept of the Modern Sport Performance Tee's white upper-back GOOOL Athletics print, true royal blue garment",
            caption: "Back print detail - concept render. Not a photograph of a manufactured sample.",
          },
        ],
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "tshirt",
    supplierType: "unassigned",
    isActive: true,
    availableForSale: true,
    isLimitedDrop: false,
    dropVersion: null,
    dropLimit: null,
    dropSoldCount: 0,
    customNameAvailable: false,
    customNumberAvailable: false,
    customizationPriceCents: 0,
    disclosure:
      "In development. Final garment and print details are being checked with the production partner. Product photography follows sample approval.",
  },
];

// ── Data access (swap these for Supabase queries later) ───────

export function getProducts(): Product[] {
  return products.filter((p) => p.isActive);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug && p.isActive);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id && p.isActive);
}

export function getLimitedDropProducts(): Product[] {
  return products.filter((p) => p.isActive && p.isLimitedDrop);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return products.filter((p) => p.isActive && p.category === category);
}

export function getJerseysByDrop(version: string): Product[] {
  return products.filter(
    (p) => p.isActive && p.category === "jersey" && p.dropVersion === version
  );
}
