#!/usr/bin/env python
"""Resolution gate for brand-assets/avatars (owner decision 2026-09-29).

    python scripts/check-avatars.py            list every avatar file under the gate
    python scripts/check-avatars.py --write    also rewrite the per-file table in AVATARS.md

Any still whose long edge is under 1024 px is THUMBNAIL, NOT USABLE: it
stays in place so the file name is stable, but it is never handed to
Claude Design or Higgsfield. Videos are listed, not gated. Exit code 1
while anything is under the gate, so the number left to replace is one
command away.
"""
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AVATARS = os.path.join(ROOT, "brand-assets", "avatars")
GATE = 1024
STILLS = (".png", ".jpg", ".jpeg", ".webp")
VIDEOS = (".mp4", ".mov", ".webm")


def video_size(path):
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height",
             "-of", "json", path], capture_output=True, text=True, timeout=20).stdout
        s = json.loads(out)["streams"][0]
        return int(s["width"]), int(s["height"])
    except Exception:
        return None


def scan():
    from PIL import Image
    rows = []
    for avatar in sorted(os.listdir(AVATARS)):
        folder = os.path.join(AVATARS, avatar)
        if not os.path.isdir(folder):
            continue
        for name in sorted(os.listdir(folder)):
            path = os.path.join(folder, name)
            ext = os.path.splitext(name)[1].lower()
            if ext in STILLS:
                w, h = Image.open(path).size
                ok = max(w, h) >= GATE
                rows.append((avatar, name, f"{w} x {h}", "usable" if ok else "THUMBNAIL, NOT USABLE", ok))
            elif ext in VIDEOS:
                dims = video_size(path)
                size = f"{dims[0]} x {dims[1]}" if dims else "video"
                rows.append((avatar, name, size, "video, not gated", True))
    return rows


def table(rows):
    lines = ["| Avatar | File | Pixels | Gate |", "|---|---|---|---|"]
    for avatar, name, size, status, _ in rows:
        lines.append(f"| {avatar} | `{name}` | {size} | {status} |")
    return "\n".join(lines)


def write_md(rows):
    path = os.path.join(AVATARS, "AVATARS.md")
    with open(path, encoding="utf-8") as f:
        md = f.read()
    under = sum(1 for r in rows if not r[4])
    block = (
        "<!-- gate:start (generated by scripts/check-avatars.py --write; do not edit by hand) -->\n"
        f"Gate: long edge at least {GATE} px. Files under the gate: **{under}**.\n\n"
        + table(rows) + "\n<!-- gate:end -->"
    )
    if not re.search(r"<!-- gate:start.*?<!-- gate:end -->", md, flags=re.S):
        raise SystemExit("AVATARS.md has no gate markers; add them once, then rerun.")
    new = re.sub(r"<!-- gate:start.*?<!-- gate:end -->", lambda _: block, md, flags=re.S)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(new)


def main():
    rows = scan()
    under = [r for r in rows if not r[4]]
    if "--write" in sys.argv:
        write_md(rows)
    if under:
        print(f"{len(under)} avatar file(s) under the {GATE} px gate:")
        for avatar, name, size, _, _ in under:
            print(f"  {avatar}/{name}  {size}")
    else:
        print(f"All avatar stills are at or above {GATE} px on the long edge.")
    sys.exit(1 if under else 0)


if __name__ == "__main__":
    main()
