/* Reproducible extraction of the approved v84 presentation, not its demo cart/router. */
const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const postcss = require('postcss');
const selectorParser = require('postcss-selector-parser');
const source = path.resolve(process.argv[2] || '../output/v84-discovery-2026-10-05/reference-audit/public');
const target = path.resolve('src/v84');
fs.mkdirSync(target, { recursive: true });
fs.mkdirSync('public/v84', { recursive: true });
fs.cpSync(path.join(source, 'assets'), 'public/v84/assets', { recursive: true });
for (const name of ['participation-agreement.html', 'story-participation-agreement.html', 'intake-privacy.html']) {
  fs.copyFileSync(path.join(source, name), path.join('public', name));
}
const app = fs.readFileSync(path.join(source, 'app.js'), 'utf8');
const wanted = new Set(['strike', '$', '$$', 'escapeHTML', 'brandLockup', 'brandDivider', 'brandLabel', 'goalWord', 'storyClips', 'goalIntroObserver', 'hero', 'home', 'landing', 'about', 'goalCampaign', 'references', 'detail']);
function statements(text, pick) {
  const tree = ts.createSourceFile('reference.js', text, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
  return tree.statements.filter(node => pick(node, tree)).map(node => node.getText(tree)).join('\n');
}
function names(node) {
  if (ts.isFunctionDeclaration(node)) return [node.name?.text];
  if (ts.isVariableStatement(node)) return node.declarationList.declarations.map(d => d.name.getText());
  return [];
}
const appBase = statements(app, node => names(node).some(n => wanted.has(n)));
const appEvents = app.slice(app.indexOf('// Personal-story composition'));
const depth = app.slice(app.indexOf('// Pointer-led depth'), app.indexOf('// Private preview only'));
fs.writeFileSync(path.join(target,'depth.js'), `// Approved v84 motion, with React lifecycle cleanup.
export function mountDepth(root) {
 const abort = new AbortController();
 const document = { addEventListener: (type, fn) => root.addEventListener(type, fn, {signal:abort.signal}) };
 const window = { addEventListener: (type, fn) => globalThis.window.addEventListener(type, fn, {signal:abort.signal}) };
 const $$ = selector => [...root.querySelectorAll(selector)];
 ${depth}
 return () => { abort.abort(); cancelAnimationFrame(depthFrame); $$('.world-card,.product-card,.btn,.depth-button').forEach(resetDepth); };
}
`);
const pieces = ['match-terms.js','story-terms.js','share-goals.js','kit-wear.js','intake.js'].map(name => fs.readFileSync(path.join(source,name),'utf8'));
let joined = appBase + '\n' + pieces.join('\n') + '\n' + appEvents;
// Literal path conversion covers markup and dynamically assigned asset URLs alike.
joined = joined.replaceAll("import('./assets/", "import(/* webpackIgnore: true */ '/v84/assets/").replace(/(?<!\/v84\/)assets\//g, '/v84/assets/')
  .replaceAll('href="#/collection"', 'href="/shop"').replaceAll('href="#/support"','href="/contact"').replaceAll('href="#/', 'href="/')
  .replaceAll('href="participation-agreement.html"','href="/participation-agreement.html"')
  .replaceAll('href="story-participation-agreement.html"','href="/story-participation-agreement.html"')
  .replaceAll('href="intake-privacy.html"','href="/intake-privacy.html"');
const declarations = statements(joined, node => ts.isFunctionDeclaration(node) || ts.isVariableStatement(node));
const bindings = statements(joined, node => !(ts.isFunctionDeclaration(node) || ts.isVariableStatement(node) || (ts.isExpressionStatement(node) && ts.isStringLiteral(node.expression))));
const bridge = `// Generated by scripts/import-v84.cjs from approved v84. Do not hand-edit.
import { sendIntake as uploadIntake } from './upload-client';
/** @param {HTMLElement | null} root */
export function referenceExperience(root = null) {
 const nativeDocument = typeof globalThis.document === 'undefined' ? null : globalThis.document;
 const nativeWindow = typeof globalThis.window === 'undefined' ? null : globalThis.window;
 const abort = new AbortController();
 const frames = new Set();
 const document = nativeDocument && new Proxy(nativeDocument, { get(target, key) {
   if (key === 'querySelector') return selector => selector === '#header' ? nativeDocument.querySelector(selector) : root.querySelector(selector);
   if (key === 'querySelectorAll') return selector => root.querySelectorAll(selector);
   if (key === 'getElementById') return id => root.querySelector('#' + id);
   if (key === 'addEventListener') return (name, fn, options) => root.addEventListener(name, fn, { ...(typeof options === 'boolean' ? { capture: options } : options), signal: abort.signal });
   const value = Reflect.get(target, key, target); return typeof value === 'function' ? value.bind(target) : value;
 }, set(target,key,value) { return Reflect.set(target,key,value,target); } });
 const window = nativeWindow && new Proxy(nativeWindow, { get(target, key) {
   if (key === 'addEventListener') return (name, fn, options) => target.addEventListener(name, fn, { ...options, signal: abort.signal });
   const value = Reflect.get(target, key, target); return typeof value === 'function' ? value.bind(target) : value;
 } });
 const requestAnimationFrame = fn => { if (!root || abort.signal.aborted) return 0; const id = nativeWindow.requestAnimationFrame(() => { frames.delete(id); if (!abort.signal.aborted) fn(); }); frames.add(id); return id; };
 const products = []; const productById = () => null;
 const productGrid = () => '<div data-v84-slot="products"></div>';
 const landingTabs = () => '<div data-v84-slot="products"></div>';
 ${declarations.replace(/async function sendIntake\([\s\S]*?\n}\n(?=function kitRequestPayload)/, '')}
 function sendIntake(...args) { return uploadIntake(...args); }
 function openDialog(id) { const d = document.getElementById(id); if (d && !d.open) d.showModal(); }
 return {
   markup(route) { return ({ home, men: () => landing('men'), women: () => landing('women'), about, references, story: goalCampaign, kit: kitWearPage, match: shareGoalsPage }[route] || about)(); },
   mount(route, sample) {
     ${bindings}
     root.addEventListener('click', event => {
       const t = event.target.closest('button,a'); if (!t) return;
       if (t.matches('[data-close]')) t.closest('dialog')?.close();
       if (t.matches('[data-scroll]')) { event.preventDefault(); document.getElementById(t.dataset.scroll)?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); }
     }, { signal: abort.signal });
     root.querySelectorAll('dialog').forEach(d => d.addEventListener('click', event => { if (event.target !== d) return; const r = d.getBoundingClientRect(); if (event.clientX < r.left || event.clientX > r.right || event.clientY < r.top || event.clientY > r.bottom) d.close(); }, { signal: abort.signal }));
     if (route === 'story') setupGoalIntroReveal();
     if (route === 'kit') { syncKit(); drawKitNumbers(); }
     if (route === 'match') { syncMatchCategory(); if (sample) showMatchReview({ sample: true, category: sample }); }
     return () => { abort.abort(); frames.forEach(id => nativeWindow.cancelAnimationFrame(id)); goalIntroObserver?.disconnect(); clearKitFiles(); clearStoryClips(); clearGoalVideos(); };
   }
 };
}
`;
fs.writeFileSync(path.join(target,'reference-experience.js'), bridge);
for (const name of ['style.css','kit-wear.css']) {
  const css = postcss.parse(fs.readFileSync(path.join(source,name),'utf8'));
  css.walkAtRules('import',rule=>rule.remove());
  css.walkRules(rule=>{
    if (rule.parent.type === 'atrule' && /keyframes$/.test(rule.parent.name)) return;
    rule.selectors = rule.selectors.map(selector => {
      if (selector === ':root' || selector === 'body') return '.v84';
      if (selector.startsWith('html')) return selector;
      const scoped = selectorParser(tree => tree.walkTags(tag => {
        if (tag.value === 'header' || tag.value === 'footer') tag.replaceWith(selectorParser.id({ value: tag.value === 'header' ? 'header' : 'site-footer' }));
      })).processSync(selector);
      return ':where(.v84) ' + scoped;
    });
  });
  fs.writeFileSync(path.join(target,name),css.toString().replaceAll('assets/','/v84/assets/').replaceAll('#/collection','/shop').replaceAll('#/support','/contact').replaceAll('#/','/'));
}
console.log('Imported v84 presentation, private workflow controllers and exact assets. Demo cart/router excluded.');
const serverTarget = path.resolve('src/lib/intake');
fs.mkdirSync(serverTarget, { recursive: true });
const worker = fs.readFileSync(path.join(source, '../server/worker.mjs'), 'utf8');
const validation = statements(worker, node => names(node).some(n => ['fail','str','cleanPayload','filesMeta','checkMagic'].includes(n)));
fs.writeFileSync(path.join(serverTarget,'validation.mjs'), '// Extracted unchanged validation from approved v84. Transport and authorization are implemented separately.\n' + validation + '\nexport { cleanPayload, filesMeta, checkMagic };\n');
fs.writeFileSync(path.join(serverTarget,'agreements.json'), JSON.stringify(Object.fromEntries(['participation-agreement.html','story-participation-agreement.html'].map(name => [name, fs.readFileSync(path.join(source,name),'utf8')])), null, 2));
const adminHtml = fs.readFileSync(path.join(source,'admin.html'),'utf8').split('<body>')[1].split('</body>')[0]
  .replace('<a class="underline" href="/signout-with-chatgpt?return_to=%2Fadmin">Sign out</a>', '<button class="underline" id="owner-signout">Sign out</button>');
fs.writeFileSync(path.join(target,'admin-markup.json'), JSON.stringify(adminHtml));
let adminJs = fs.readFileSync(path.join(source,'admin.js'),'utf8').replaceAll('/signin-with-chatgpt?return_to=%2Fadmin','/admin/sign-in').replaceAll('Sign in with ChatGPT','Owner sign in');
fs.writeFileSync(path.join(target,'admin-controller.js'), `// Approved v84 dashboard, scoped to the authenticated React route.
export function mountAdmin(root) {
 const abort = new AbortController();
 const nativeDocument = globalThis.document, nativeWindow = globalThis.window;
 const document = new Proxy(nativeDocument,{get(target,key) {
  if(key==='querySelector') return selector=>root.querySelector(selector);
  if(key==='querySelectorAll') return selector=>root.querySelectorAll(selector);
  if(key==='addEventListener') return (type,fn)=>root.addEventListener(type,fn,{signal:abort.signal});
  const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value;
 }});
 const window = new Proxy(nativeWindow,{get(target,key) {
  if(key==='addEventListener') return (type,fn)=>target.addEventListener(type,fn,{signal:abort.signal});
  const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value;
 }});
 ${adminJs}
 root.querySelector('#owner-signout').addEventListener('click',async()=>{
  try { await api('/api/admin/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'signout'})}); location.assign('/admin/sign-in'); }
  catch(e) { document.querySelector('#admin-access').hidden=false; document.querySelector('#admin-access').textContent=e.message; }
 },{signal:abort.signal});
 const refresh=setInterval(()=>api('/api/admin/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})}).catch(()=>{location.assign('/admin/sign-in');}),10*60*1000);
 return ()=>{abort.abort();clearTimeout(timer);clearInterval(refresh);loadRevision++;};
}
`);
const adminCss = postcss.parse(fs.readFileSync(path.join(source,'admin.css'),'utf8'));
adminCss.walkAtRules('import',r=>r.remove());
adminCss.walkRules(r=>{ if(r.parent.type==='atrule' && /keyframes$/.test(r.parent.name)) return; r.selectors=r.selectors.map(s=>s==='body'||s===':root'?'.v84-admin':':where(.v84-admin) '+s); });
fs.writeFileSync(path.join(target,'admin.css'),adminCss.toString());
