-- Tee mockups live; jersey galleries re-shot (Men's 2 model, no alt view).
update public.products set images = '[{"src": "/products/brush-script-tee.webp", "alt": "PORTUGOOOL Brush Script Tee \u2014 front"}, {"src": "/products/brush-script-tee-back.webp", "alt": "PORTUGOOOL Brush Script Tee \u2014 back"}]'::jsonb where slug = 'brush-script-tee';
update public.products set images = '[{"src": "/products/goool-tee.webp", "alt": "GOOOOOOOL!!! Tee \u2014 front"}, {"src": "/products/goool-tee-back.webp", "alt": "GOOOOOOOL!!! Tee \u2014 back"}]'::jsonb where slug = 'goool-tee';
update public.products set images = '[{"src": "/products/vamos-tee.webp", "alt": "Vamos Portugooool Tee \u2014 front"}, {"src": "/products/vamos-tee-back.webp", "alt": "Vamos Portugooool Tee \u2014 back"}]'::jsonb where slug = 'vamos-tee';
update public.products set images = '[{"src": "/products/lisbon-to-the-world-tee.webp", "alt": "From Lisbon to the World Tee \u2014 front"}, {"src": "/products/lisbon-to-the-world-tee-back.webp", "alt": "From Lisbon to the World Tee \u2014 back"}]'::jsonb where slug = 'lisbon-to-the-world-tee';
update public.products set images = '[{"src": "/products/match-day-tee.webp", "alt": "Match Day Tee \u2014 front"}, {"src": "/products/match-day-tee-back.webp", "alt": "Match Day Tee \u2014 back"}]'::jsonb where slug = 'match-day-tee';
update public.products set images = '[{"src": "/products/we-dont-whisper-goals-tee.webp", "alt": "We Don''t Whisper Goals Tee \u2014 front"}, {"src": "/products/we-dont-whisper-goals-tee-back.webp", "alt": "We Don''t Whisper Goals Tee \u2014 back"}]'::jsonb where slug = 'we-dont-whisper-goals-tee';
update public.products set images = '[{"src": "/products/home-red-jersey.webp", "alt": "Home Red Jersey \u2014 front, on model"}, {"src": "/products/home-red-jersey-back.webp", "alt": "Home Red Jersey \u2014 back, ready for custom name and number"}]'::jsonb where slug = 'home-red-jersey';
update public.products set images = '[{"src": "/products/away-white-jersey.webp", "alt": "Away White Jersey \u2014 front, on model"}, {"src": "/products/away-white-jersey-back.webp", "alt": "Away White Jersey \u2014 back, ready for custom name and number"}]'::jsonb where slug = 'away-white-jersey';
update public.products set images = '[{"src": "/products/blackout-edition-jersey.webp", "alt": "Blackout Edition Jersey \u2014 front, on model"}, {"src": "/products/blackout-edition-jersey-back.webp", "alt": "Blackout Edition Jersey \u2014 back, ready for custom name and number"}]'::jsonb where slug = 'blackout-edition-jersey';
update public.products set images = '[{"src": "/products/emerald-edition-jersey.webp", "alt": "Emerald Edition Jersey \u2014 front, on model"}, {"src": "/products/emerald-edition-jersey-back.webp", "alt": "Emerald Edition Jersey \u2014 back, ready for custom name and number"}]'::jsonb where slug = 'emerald-edition-jersey';
